version: '3.8'

services:
  db_production:
    image: postgres:15-alpine
    container_name: db_production
    restart: unless-stopped
    environment:
      POSTGRES_USER: vazzuniverse
      POSTGRES_PASSWORD: vazzuniverse
      POSTGRES_DB: vazzuniverse  
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"  
      TZ: Asia/Jakarta
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/prod-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vazzuniverse -d vazzuniverse"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  db_development:
    image: postgres:15-alpine
    container_name: db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: myapp_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - pgdev_data:/var/lib/postgresql/data
      - ./init-scripts/dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d myapp_dev"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/pg-data/prod  
  pgdev_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/pg-data/dev

networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1