services:
  db_production:
    image: postgres:15-alpine
    container_name: db_production
    restart: unless-stopped
    environment:
      POSTGRES_USER: vazzuniverse
      POSTGRES_PASSWORD: vazzuniverse
      POSTGRES_DB: vazzuniverse  
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"  
      TZ: Asia/Jakarta
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/prod-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vazzuniverse -d vazzuniverse"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: backend_topup
    ports:
      - "4000:4000"
    depends_on:
      - db_production
    networks:
      - backend-network
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env.production
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:4000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s   
    

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./pg-data/prod  

networks:
  backend-network:
    driver: bridge