export const ERROR_CODES = {
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    CONFLICT : "CONFLICT",
    SESSION_EXPIRED: "SESSION_EXPIRED"
  } as const;
  
  export type ErrorCode = keyof typeof ERROR_CODES;