// error.ts
export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  DB_INIT_ERROR: "DB_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  DB_PANIC: "DB_PANIC",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  CONFLICT: "CONFLICT",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  MIGRATION_ERROR: "DB_ERROR",
  MIGRATION_IN_PROGRESS: "DB_ERROR",
  MIGRATION_NOT_FOUND: "NOT_FOUND",
  INVALID_CONNECTION: "DB_ERROR",
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
