name: Backend Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 103.127.98.128 >> ~/.ssh/known_hosts
          
      - name: Setup remote directory structure
        run: |
          ssh vazzuniverse@103.127.98.128 "mkdir -p ~/backend/pg-data/prod"
          
      - name: Copy Docker files and project files
        run: |
          scp -r docker/ prisma/ package*.json tsconfig.json .env.production src/ vazzuniverse@103.127.98.128:~/backend/
          
      - name: Deploy to VPS with Docker
        run: |
          ssh vazzuniverse@103.127.98.128 "cd ~/backend && \
            cd docker && \
            docker compose down || true && \
            docker compose up -d --build"
            
      - name: Verify deployment
        run: |
          ssh vazzuniverse@103.127.98.128 "docker ps | grep backend_topup && \
            echo 'Backend deployed successfully!' || \
            echo 'Backend deployment failed!'"